[build]
dockerfile = "Dockerfile"
watchPatterns = ["central_exchange/**"]

[build.args]
NO_CACHE = "202601271656"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
