apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cre-exchange-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: cre.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cre-exchange
            port:
              number: 8080
